### ISSUE TITLE
Error occur with Eslint

### ISSUE THREAD

**Issue by freedomlang** [FormidableLabs/webpack-dashboard#173]
###### Steps to reproduce the problem
After setting the 'extends' for eslint, the webpack-dashboard just show up the errors below: 
```
TypeError: Cannot read property 'slice' of null
    at /mnt/D/projects/bigWeb/node_modules/blessed/lib/program.js:2543:35
    at Array.forEach (native)
    at Program._attr (/mnt/D/projects/bigWeb/node_modules/blessed/lib/program.js:2542:11)
    at ScrollableBox.Element._parseTags (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/element.js:498:26)
    at ScrollableBox.Element.parseContent (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/element.js:393:22)
    at ScrollableBox.Element.setContent (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/element.js:335:8)
    at ScrollableBox.Element.setLine (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/element.js:2487:15)
    at ScrollableBox.Element.pushLine (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/element.js:2525:34)
    at ScrollableBox.Log.log.Log.add (/mnt/D/projects/bigWeb/node_modules/blessed/lib/widgets/log.js:61:18)
    at /mnt/D/projects/bigWeb/node_modules/webpack-dashboard/dashboard/index.js:87:22
    at Array.forEach (native)
    at Dashboard.setData (/mnt/D/projects/bigWeb/node_modules/webpack-dashboard/dashboard/index.js:40:11)
    at Compiler.<anonymous> (/mnt/D/projects/bigWeb/node_modules/webpack-dashboard/plugin/index.js:90:13)
    at Compiler.applyPlugins (/mnt/D/projects/bigWeb/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/mnt/D/projects/bigWeb/node_modules/webpack/lib/Compiler.js:91:17)
    at /mnt/D/projects/bigWeb/node_modules/webpack/lib/Compiler.js:74:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
====================================================================

###### Please provide a gist of relevant files

I've put the relavent files cause this error to [gist](https://gist.github.com/freedomlang/bd064d1f8e461ff19f3839d3d76b7ec4)

1. package.json (npm run dev)
2. webpack.config.js
2. eslintrc

====================================================================

###### More Details

- operating system: Linux「Debian」
- terminal: Zsh
- version of webpack-dashboard: 0.4.0
- the output of running `echo $TERM`: xterm-256color

**Comment by kenwheeler** [comment]
Does this work running webpack without webpack dashboard?

**Comment by freedomlang** [comment]
eslint works fine without webpack dashboard

**Comment by djdifee** [comment]
Just ran into this myself (with version 1.0.0-5), did you manage to find a workaround @freedomlang?

**Comment by freedomlang** [comment]
not yet. (ノ﹏ヽ)

**Comment by ryan-roemer** [comment]
Can folks update to newly released `^1.0.0` and see if this is still an issue?

If so, can someone open a minimal repository with the error and install + reproduction steps so we have something to dig in and analyze? Thanks!

**Comment by freedomlang** [comment]
solved(with 1.0.0 On Mac)，i'll give another try on devian

**Comment by djdifee** [comment]
Works like a charm here (also Mac)

**Comment by ryan-roemer** [comment]
Yay! If folks hit this with 1.0, please open a new issue.
