### ISSUE TITLE
Logs are all white

### ISSUE THREAD

**Issue by gabrielhpugliese** [FormidableLabs/webpack-dashboard#177]
> Please provide a description of the bug / issue, and provide the details below:

I'm probably missing something in the process, but webpack log color is all white. See pictures and config below:

`webpack -w` output:

![image](https://user-images.githubusercontent.com/1252818/28375027-b3086484-6ca6-11e7-9ecb-b58e750399a9.png)

`webpack-dashboard` output:

![image](https://user-images.githubusercontent.com/1252818/28375071-cf4cb938-6ca6-11e7-81d7-abad6c3a7f63.png)

I'm using the webpack plugin and running the commands in different windows. First I run the dashboard then the webpack watch.

====================================================================

###### More Details

- What operating system are you on? 

macOS Sierra

- What terminal application are you using?

iTerm2 + tmux

- What version of webpack-dashboard are you using?

0.4.0

- What is the output of running `echo $TERM`?

xterm-256color

**Comment by ryan-roemer** [comment]
@gabrielhpugliese -- Can you upgrade to `^1.0.0` and try again?

If the issue persists, can you create a minimal repository with install + reproduction steps so that we can jump in and more quickly figure out what's going on?

**Comment by gabrielhpugliese** [comment]
The log is still white using (1.0.1):
![image](https://user-images.githubusercontent.com/1252818/32541571-4c7abde4-c470-11e7-9c3c-8319884baebb.png)

Also got an error after 1min:
```
TypeError: Cannot read property 'meta' of undefined
    at assets.filter.map.asset (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/webpack-dashboard/utils/format-assets.js:28:41)
    at Array.map (<anonymous>)
    at _.flatMap.assets (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/webpack-dashboard/utils/format-assets.js:24:8)
    at l (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/lodash/lodash.min.js:6:443)
    at uu (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/lodash/lodash.min.js:67:252)
    at On.flatMap (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/lodash/lodash.min.js:99:101)
    at l (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/lodash/lodash.min.js:50:137)
    at resolveAssets (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/webpack-dashboard/utils/format-assets.js:32:4)
    at printAssets (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/webpack-dashboard/utils/format-assets.js:36:18)
    at formatAssets (/Users/gabrielhpugliese/Workspace/integration/personio/node_modules/webpack-dashboard/utils/format-assets.js:55:10)
```

**Comment by ryan-roemer** [comment]
@gabrielhpugliese -- For the error, can you upgrade to `webpack-dashboard@^1.0.2`? @DrSensor 's fix in #221 should take care of that.

For the log white thing, can you create a minimal repository with install + reproduction steps so I can see what you see? This will enable us to diagnose things much faster...

**Comment by gabrielhpugliese** [comment]
Error is gone, but logs are still white. Will try to create a reproducible repo (will put on my todo list here).

**Comment by gabrielhpugliese** [comment]
I've implemented webpack-dev-server and it's colored. 
Previous script command was:

`"start": "NODE_ENV=\"development\" concurrently --kill-others -r \"webpack-dashboard -m\" \"webpack --watch > /dev/null 2>&1\"",`

Changed to:

`"start": "NODE_ENV=\"development\" concurrently --kill-others -r \"webpack-dashboard -m\" \"webpack-dev-server --hot --inline > /dev/null 2>&1\"",`

**Comment by ryan-roemer** [comment]
Closing due to inactivity now that we've released `webpack-dashboard@^2`. If issue persists in new dashboard, please create a minimal repository with code + install steps + error reproduction steps and we'll look into this.
