### ISSUE TITLE
Webpack v4 plugin support

### ISSUE THREAD

**Issue by switz** [FormidableLabs/webpack-dashboard#240]
> Please provide a description of the bug / issue, and provide the details below:

I'm seeing these deprecation warnings when running webpack-dashboard in webpack v4 with `process.traceDeprecation = true;` in my webpack config:

```
$ node_modules/.bin/webpack-dev-server --config ./webpack.config.js
(node:16541) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at DashboardPlugin.apply (/Users/daniel/y/iui/node_modules/webpack-dashboard/plugin/index.js:98:14)
    at webpack (/Users/daniel/y/iui/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at Object.<anonymous> (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:16541) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at DashboardPlugin.apply (/Users/daniel/y/iui/node_modules/webpack-dashboard/plugin/index.js:117:14)
    at webpack (/Users/daniel/y/iui/node_modules/webpack/lib/webpack.js:37:12)
    at startDevServer (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:379:16)
    at processOptions (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:361:5)
    at Object.<anonymous> (/Users/daniel/y/iui/node_modules/webpack-dev-server/bin/webpack-dev-server.js:504:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

I'm also seeing a lot of `Worker error Error: No code sections found` but I see that is being discussed in #234.

====================================================================

###### Steps to reproduce the problem

Add `new DashboardPlugin()` to plugins in webpack v4.

====================================================================

###### More Details

- What operating system are you on?
OS X 10.12
- What terminal application are you using?
iTerm 2
- What version of webpack-dashboard are you using?
1.1.1
- What is the output of running `echo $TERM`?
xterm-256color

**Comment by ryan-roemer** [comment]
Haven't even looked at this yet, but guessing we'll need something analogous to: https://github.com/FormidableLabs/webpack-stats-plugin/blob/master/lib/stats-writer-plugin.js#L60-L66

**Comment by jharris4** [comment]
FYI a plugin I maintain started giving the `Tapable.apply is deprecated` warning after upgrading to webpack 4, and I managed to find the commit to webpack where they updated all the internal plugins to fix that:

https://github.com/webpack/webpack/commit/7dd41b55c6aa8fdac4b643acadc65ac5fc321c36#diff-5d04086b4365820a456acec22b899956

**Comment by IamCarbonMan** [comment]
Is this bug going to be looked at further? It's been broken for several months now and essentially makes this entire repo deprecated, since the webpack community has basically fully migrated to webpack v4.

**Comment by ryan-roemer** [comment]
Yes, I've been working on the `inspectpack` port to a completely new version for longer than this issue is open and going to bring that (as the underlying engine to webpack-dashboard) to webpack-dashboard soon. (Things will also get a lot faster as the new inspectpack uses only the stats object instead of the raw bundle).

In the meantime @IamCarbonMan , we'd be open to a stop-gap PR to adjust the plugin hooks for webpack@v4 compatibility.

**Comment by IamCarbonMan** [comment]
I'll try and submit something just to make things work for now. Hopefully the underlying stuff works out before too long.

**Comment by sunny920406** [comment]
mark

**Comment by ztoben** [comment]
@IamCarbonMan, I can put in a PR if you don't have time to get one in. Just don't want to work on one if you've started it already.

**Comment by ryan-roemer** [comment]
HI Folks, I've actually just started working on this a day ago as inspectpack@3 is almost ready (one more feature PR and should be good to go -- it's been in a private repo, hence lack of visibility). I'll take this on as part of part of the integration of the new inspectpack.

It may still be a week or two depending on my free time, but this is literally what I'm working on now, so thanks all around for your patience.

(As a helpful teaser, the new inspectpack has way fewer dependencies (no binary deps anymore), is tested for all webpack versions 1-4, and is way, way, way faster).
