### ISSUE TITLE
ELIFECYCLE Error when starting

### ISSUE THREAD

**Issue by CallawayJay** [FormidableLabs/webpack-dashboard#252]
I'll have it running for a while, I'll close it out.  Run npm start and I'll get the following error:

`~/web/contract-summary › npm start

> contract-summary@0.1.0 start /Users/JayStarr/web/contract-summary
> webpack-dashboard -m -- webpack-dev-server --config config/webpack.config.js --open --env.local --hot

internal/process.js:172
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1026:11)
    at process.kill (internal/process.js:172:13)
    at process.on (/Users/JayStarr/web/contract-summary/node_modules/webpack-dashboard/bin/webpack-dashboard.js:89:15)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at Screen.Dashboard.screen.key (/Users/JayStarr/web/contract-summary/node_modules/webpack-dashboard/dashboard/index.js:84:15)
    at Screen.EventEmitter._emit (/Users/JayStarr/web/contract-summary/node_modules/blessed/lib/events.js:94:20)
    at Screen.EventEmitter.emit (/Users/JayStarr/web/contract-summary/node_modules/blessed/lib/events.js:114:17)
    at Program.<anonymous> (/Users/JayStarr/web/contract-summary/node_modules/blessed/lib/widgets/screen.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contract-summary@0.1.0 start: `webpack-dashboard -m -- webpack-dev-server --config config/webpack.config.js --open --env.local --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contract-summary@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/JayStarr/.npm/_logs/2018-07-13T15_22_42_717Z-debug.log`

I'll go and kill all node processes but that won't work.  I'm trying to run on port 8080 so I ran the following command to see if anything else is trying to listen on that port:

`sudo lsof -i -n -P | grep TCP`

And this is the output:

`~/web/contract-summary › sudo lsof -i -n -P | grep TCP
vpnagentd    72           root    5u  IPv4 0xfd5521e048461377      0t0  TCP 127.0.0.1:29754 (LISTEN)
apsd        102           root    7u  IPv4 0xfd5521e04f5a38f7      0t0  TCP 192.168.1.6:49242->17.249.12.153:5223 (ESTABLISHED)
apsd        102           root    9u  IPv4 0xfd5521e04f5a38f7      0t0  TCP 192.168.1.6:49242->17.249.12.153:5223 (ESTABLISHED)
httpd       104           root    4u  IPv6 0xfd5521e0490156cf      0t0  TCP *:80 (LISTEN)
httpd       104           root    5u  IPv4 0xfd5521e0490238f7      0t0  TCP *:* (CLOSED)
nfsd        254           root    7u  IPv4 0xfd5521e04677ef97      0t0  TCP *:1023 (LISTEN)
nfsd        254           root    8u  IPv6 0xfd5521e046782b4f      0t0  TCP *:1022 (LISTEN)
nfsd        254           root    9u  IPv4 0xfd5521e04677e637      0t0  TCP *:2049 (LISTEN)
nfsd        254           root   10u  IPv6 0xfd5521e04678310f      0t0  TCP *:2049 (LISTEN)
cupsd       258           root    7u  IPv6 0xfd5521e0467836cf      0t0  TCP *:631 (LISTEN)
cupsd       258           root    8u  IPv4 0xfd5521e0484638f7      0t0  TCP *:631 (LISTEN)
rpc.statd   260           root    7u  IPv4 0xfd5521e049327377      0t0  TCP *:1021 (LISTEN)
rpc.statd   260           root    8u  IPv6 0xfd5521e049014b4f      0t0  TCP *:1019 (LISTEN)
rpc.lockd   263           root    6u  IPv4 0xfd5521e0494cc377      0t0  TCP *:1017 (LISTEN)
rpc.lockd   263           root    7u  IPv6 0xfd5521e04901458f      0t0  TCP *:1012 (LISTEN)
rpcbind     264         daemon    4u  IPv4 0xfd5521e04677dcd7      0t0  TCP *:111 (LISTEN)
rpcbind     264         daemon    6u  IPv6 0xfd5521e04901510f      0t0  TCP *:111 (LISTEN)
httpd       317           _www    4u  IPv6 0xfd5521e0490156cf      0t0  TCP *:80 (LISTEN)
httpd       317           _www    5u  IPv4 0xfd5521e0490238f7      0t0  TCP *:* (CLOSED)
rpc.rquot   328           root    6u  IPv4 0xfd5521e0494f3377      0t0  TCP *:999 (LISTEN)
rpc.rquot   328           root    7u  IPv6 0xfd5521e0494f76cf      0t0  TCP *:996 (LISTEN)
Google      356       JayStarr   58u  IPv4 0xfd5521e0607a88f7      0t0  TCP 192.168.1.6:51614->104.192.143.1:443 (ESTABLISHED)
Google      356       JayStarr  119u  IPv4 0xfd5521e05fc8bf97      0t0  TCP 192.168.1.6:54342->104.192.138.71:443 (ESTABLISHED)
Google      356       JayStarr  148u  IPv4 0xfd5521e04e01cf97      0t0  TCP 192.168.1.6:49204->108.177.120.188:5228 (ESTABLISHED)
Google      356       JayStarr  153u  IPv4 0xfd5521e0494f4637      0t0  TCP 192.168.1.6:51828->192.168.1.9:42968 (ESTABLISHED)
Google      356       JayStarr  155u  IPv4 0xfd5521e05e52acd7      0t0  TCP 192.168.1.6:60843->13.56.167.230:443 (ESTABLISHED)
Google      356       JayStarr  181u  IPv4 0xfd5521e0502db637      0t0  TCP 192.168.1.6:51849->192.168.1.9:8009 (ESTABLISHED)
Google      356       JayStarr  234u  IPv4 0xfd5521e0494daf97      0t0  TCP 192.168.1.6:58238->216.58.192.142:80 (CLOSED)
Google      356       JayStarr  247u  IPv4 0xfd5521e05f0818f7      0t0  TCP 192.168.1.6:53619->136.147.110.205:443 (ESTABLISHED)
Google      356       JayStarr  264u  IPv4 0xfd5521e054547cd7      0t0  TCP 192.168.1.6:58243->74.125.5.10:80 (CLOSED)
Google      356       JayStarr  268u  IPv4 0xfd5521e049328f97      0t0  TCP 192.168.1.6:58248->173.194.152.106:80 (CLOSED)
Google      356       JayStarr  270u  IPv4 0xfd5521e054521637      0t0  TCP 192.168.1.6:53018->151.101.1.69:443 (ESTABLISHED)
Google      356       JayStarr  333u  IPv4 0xfd5521e05daa2cd7      0t0  TCP 192.168.1.6:53025->104.16.109.18:443 (ESTABLISHED)
Google      356       JayStarr  342u  IPv4 0xfd5521e05d922f97      0t0  TCP 192.168.1.6:51846->162.247.242.21:443 (ESTABLISHED)
Google      356       JayStarr  347u  IPv4 0xfd5521e04d629f97      0t0  TCP 192.168.1.6:64073->54.86.114.0:443 (ESTABLISHED)
Google      356       JayStarr  348u  IPv4 0xfd5521e043c15cd7      0t0  TCP 192.168.1.6:64074->52.72.206.54:443 (ESTABLISHED)
Google      356       JayStarr  361u  IPv4 0xfd5521e060546f97      0t0  TCP 192.168.1.6:52004->151.101.26.110:443 (ESTABLISHED)
Google      356       JayStarr  365u  IPv4 0xfd5521e0494f58f7      0t0  TCP 192.168.1.6:62113->172.217.5.5:443 (ESTABLISHED)
Slack       361       JayStarr   61u  IPv4 0xfd5521e049022f97      0t0  TCP 192.168.1.6:59521->18.204.248.223:443 (ESTABLISHED)
Slack       361       JayStarr   64u  IPv4 0xfd5521e05f03f637      0t0  TCP 192.168.1.6:53829->52.84.216.34:443 (ESTABLISHED)
rapportd    386       JayStarr    3u  IPv4 0xfd5521e0494d9377      0t0  TCP *:49170 (LISTEN)
rapportd    386       JayStarr    4u  IPv6 0xfd5521e04678480f      0t0  TCP *:49170 (LISTEN)
commerce    434       JayStarr   13u  IPv4 0xfd5521e0553f68f7      0t0  TCP 192.168.1.6:54083->23.57.46.171:443 (ESTABLISHED)
commerce    434       JayStarr   15u  IPv4 0xfd5521e05f5d8f97      0t0  TCP 192.168.1.6:54097->23.57.46.171:443 (ESTABLISHED)
Adobe\x20   863       JayStarr   11u  IPv4 0xfd5521e050063cd7      0t0  TCP 127.0.0.1:15292 (LISTEN)
httpd      1022           _www    4u  IPv6 0xfd5521e0490156cf      0t0  TCP *:80 (LISTEN)
httpd      1022           _www    5u  IPv4 0xfd5521e0490238f7      0t0  TCP *:* (CLOSED)
httpd      1023           _www    4u  IPv6 0xfd5521e0490156cf      0t0  TCP *:80 (LISTEN)
httpd      1023           _www    5u  IPv4 0xfd5521e0490238f7      0t0  TCP *:* (CLOSED)
httpd      1024           _www    4u  IPv6 0xfd5521e0490156cf      0t0  TCP *:80 (LISTEN)
httpd      1024           _www    5u  IPv4 0xfd5521e0490238f7      0t0  TCP *:* (CLOSED)
firefox    1634       JayStarr   36u  IPv4 0xfd5521e0494d9cd7      0t0  TCP 192.168.1.6:53618->13.33.253.58:443 (ESTABLISHED)
git-remot  5632       JayStarr    7u  IPv4 0xfd5521e04f2a88f7      0t0  TCP 192.168.1.6:60306->192.30.253.113:443 (CLOSED)
git-remot  5633       JayStarr    7u  IPv4 0xfd5521e049327cd7      0t0  TCP 192.168.1.6:60307->192.30.253.113:443 (CLOSED)
git        5654       JayStarr    7u  IPv4 0xfd5521e04f2a88f7      0t0  TCP 192.168.1.6:60306->192.30.253.113:443 (CLOSED)
git-crede  5655       JayStarr    7u  IPv4 0xfd5521e04f2a88f7      0t0  TCP 192.168.1.6:60306->192.30.253.113:443 (CLOSED)
git        5659       JayStarr    7u  IPv4 0xfd5521e049327cd7      0t0  TCP 192.168.1.6:60307->192.30.253.113:443 (CLOSED)
git-crede  5661       JayStarr    7u  IPv4 0xfd5521e049327cd7      0t0  TCP 192.168.1.6:60307->192.30.253.113:443 (CLOSED)
git-remot  5769       JayStarr    7u  IPv4 0xfd5521e0494fef97      0t0  TCP 192.168.1.6:60329->192.30.253.113:443 (CLOSED)
git        5787       JayStarr    7u  IPv4 0xfd5521e0494fef97      0t0  TCP 192.168.1.6:60329->192.30.253.113:443 (CLOSED)
git-crede  5788       JayStarr    7u  IPv4 0xfd5521e0494fef97      0t0  TCP 192.168.1.6:60329->192.30.253.113:443 (CLOSED)
git-remot  5811       JayStarr    7u  IPv4 0xfd5521e054f77cd7      0t0  TCP 192.168.1.6:60338->192.30.253.113:443 (CLOSED)
git        5822       JayStarr    7u  IPv4 0xfd5521e054f77cd7      0t0  TCP 192.168.1.6:60338->192.30.253.113:443 (CLOSED)
git-crede  5823       JayStarr    7u  IPv4 0xfd5521e054f77cd7      0t0  TCP 192.168.1.6:60338->192.30.253.113:443 (CLOSED)
git-remot  6014       JayStarr    7u  IPv4 0xfd5521e0502dacd7      0t0  TCP 192.168.1.6:60380->192.30.253.113:443 (CLOSED)
git        6027       JayStarr    7u  IPv4 0xfd5521e0502dacd7      0t0  TCP 192.168.1.6:60380->192.30.253.113:443 (CLOSED)
git-crede  6028       JayStarr    7u  IPv4 0xfd5521e0502dacd7      0t0  TCP 192.168.1.6:60380->192.30.253.113:443 (CLOSED)
git-remot  6118       JayStarr    7u  IPv4 0xfd5521e048c91cd7      0t0  TCP 192.168.1.6:60404->192.30.253.113:443 (CLOSED)
git        6121       JayStarr    7u  IPv4 0xfd5521e048c91cd7      0t0  TCP 192.168.1.6:60404->192.30.253.113:443 (CLOSED)
git-crede  6122       JayStarr    7u  IPv4 0xfd5521e048c91cd7      0t0  TCP 192.168.1.6:60404->192.30.253.113:443 (CLOSED)
git-remot  6320       JayStarr    7u  IPv4 0xfd5521e0494d7637      0t0  TCP 192.168.1.6:61115->192.30.253.112:443 (CLOSED)
git        6323       JayStarr    7u  IPv4 0xfd5521e0494d7637      0t0  TCP 192.168.1.6:61115->192.30.253.112:443 (CLOSED)
git-crede  6324       JayStarr    7u  IPv4 0xfd5521e0494d7637      0t0  TCP 192.168.1.6:61115->192.30.253.112:443 (CLOSED)
git-remot  7812       JayStarr    6u  IPv4 0xfd5521e04e01b377      0t0  TCP 192.168.1.6:62316->192.30.253.112:443 (CLOSED)
git-remot  7813       JayStarr    6u  IPv4 0xfd5521e0494fe637      0t0  TCP 192.168.1.6:62315->192.30.253.112:443 (CLOSED)
git        7818       JayStarr    6u  IPv4 0xfd5521e0494fe637      0t0  TCP 192.168.1.6:62315->192.30.253.112:443 (CLOSED)
git        7819       JayStarr    6u  IPv4 0xfd5521e04e01b377      0t0  TCP 192.168.1.6:62316->192.30.253.112:443 (CLOSED)
git-crede  7820       JayStarr    6u  IPv4 0xfd5521e0494fe637      0t0  TCP 192.168.1.6:62315->192.30.253.112:443 (CLOSED)
git-crede  7821       JayStarr    6u  IPv4 0xfd5521e04e01b377      0t0  TCP 192.168.1.6:62316->192.30.253.112:443 (CLOSED)
git-remot  9292       JayStarr    7u  IPv4 0xfd5521e04677f8f7      0t0  TCP 192.168.1.6:61542->192.30.253.112:443 (CLOSED)
git-remot  9293       JayStarr    7u  IPv4 0xfd5521e04677d377      0t0  TCP 192.168.1.6:61541->192.30.253.112:443 (CLOSED)
git        9296       JayStarr    7u  IPv4 0xfd5521e04677d377      0t0  TCP 192.168.1.6:61541->192.30.253.112:443 (CLOSED)
git-crede  9297       JayStarr    7u  IPv4 0xfd5521e04677d377      0t0  TCP 192.168.1.6:61541->192.30.253.112:443 (CLOSED)
git        9300       JayStarr    7u  IPv4 0xfd5521e04677f8f7      0t0  TCP 192.168.1.6:61542->192.30.253.112:443 (CLOSED)
git-crede  9301       JayStarr    7u  IPv4 0xfd5521e04677f8f7      0t0  TCP 192.168.1.6:61542->192.30.253.112:443 (CLOSED)`

Nothing is listening on 8080... The only way i can get it working again is restarting my computer.  Then it works fine.

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)

====================================================================
###### More Details

I'm on a mac
I'm using the terminal in vs code
webpack-dashboard version 2.0.0
The output of running `echo $TERM` = xterm-256color

**Comment by ElreyB** [comment]
@CallawayJay I am attempting to recreate the issue on my computer and I want to make sure I am following the exact steps you took. 

- How long did you have it running for?
- How did you closed out the running of your app, server, and/or VSC terminal?
- What command was use to kill all your node processes?

This information will help in figuring out what actually happen and if anything warn others of this potential bug. If this is nor longer an issue would love to hear how it was resolved and we will close this issue. Thanks in advance.

**Comment by pawelkmpt** [comment]
I have similar problem when running simple: `npx webpack-dashboard -- webpack`

When I close dashboard with `q` or `esc` can see following error:

```
internal/process.js:172
      throw errors.errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at process.kill (internal/process.js:172:20)
    at process.on (/node_modules/webpack-dashboard/bin/webpack-dashboard.js:89:15)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:146:15)
    at Screen.Dashboard.screen.key (/node_modules/webpack-dashboard/dashboard/index.js:84:15)
    at Screen.EventEmitter._emit (/node_modules/blessed/lib/events.js:94:20)
    at Screen.EventEmitter.emit (/node_modules/blessed/lib/events.js:114:17)
    at Program.<anonymous> (/node_modules/blessed/lib/widgets/screen.js:593:12)
    at emitTwo (events.js:126:13)
```

Command is executed on linux server inside tmux pane.
