### ISSUE TITLE
Throwing exception

### ISSUE THREAD

**Issue by jyotirmaybanerjee** [FormidableLabs/webpack-dashboard#5]
babel-node devServer.js --harmony

/Users/jb/projects/REACT/redux/learn-redux/node_modules/webpack-dashboard/dashboard/index.js:20
  this.screen.key(['escape', 'q', 'C-c'], () => process.exit(0));
                                           ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Module._extensions..js (module.js:446:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jb/projects/REACT/redux/learn-redux/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jb/projects/REACT/redux/learn-redux/node_modules/webpack-dashboard/index.js:1:79)
    at Module._compile (module.js:428:26)

**Comment by jyotirmaybanerjee** [comment]
After moving to Node 6 I'm getting the below exception


node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/jb/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/jb/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/jb/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/jb/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/jb/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/jb/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jb/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module._compile (module.js:428:26)

**Comment by jyotirmaybanerjee** [comment]
Hurrah .. It is working now. 
The second issue was due to babel-register hook. 

Thanks. Closing the issue.
