### ISSUE TITLE
Quitting on Windows throws exception and doesn't kill process

### ISSUE THREAD

**Issue by corinnaerin** [FormidableLabs/webpack-dashboard#93]
> Please provide a description of the bug / issue, and provide the details below:

When I try to quit webpack-dashboard using `ctrl-c` or `q`, I get the following exception, and the process is not killed:

```
node.js:777
        throw errnoException(err, 'kill');
        ^

Error: kill ESRCH
    at exports._errnoException (util.js:870:11)
    at process.kill (node.js:777:15)
    at process.<anonymous> (C:\Users\Corinna\Code\nodeapptemplate\node_modules\webpack-dashboard\bin\webpack-dashboard.js:68:11)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process.exit (node.js:750:17)
    at Screen.<anonymous> (C:\Users\Corinna\Code\nodeapptemplate\node_modules\webpack-dashboard\dashboard\index.js:29:13)
    at Screen.EventEmitter._emit (C:\Users\Corinna\Code\nodeapptemplate\node_modules\webpack-dashboard\node_modules\blessed\lib\events.js:94:20)
    at Screen.EventEmitter.emit (C:\Users\Corinna\Code\nodeapptemplate\node_modules\webpack-dashboard\node_modules\blessed\lib\events.js:114:17)
    at Program.<anonymous> (C:\Users\Corinna\Code\nodeapptemplate\node_modules\webpack-dashboard\node_modules\blessed\lib\widgets\screen.js:593:12)
```

###### Please provide a gist of relevant files

https://gist.github.com/corinnaerin/9872ad83f2b101c153ac91193273c860

====================================================================

###### More Details

- What operating system are you on? Windows 10
- What terminal application are you using? IntelliJ, tried with both Git Bash or cmd.exe
- What version of webpack-dashboard are you using? 0.1.6
- What is the output of running `echo $TERM`? `xterm` for Git Bash, nothing for cmd

**Comment by kenwheeler** [comment]
Lets continue this in #83
